local mark = require('harpoon.mark')
local ui = require('harpoon.ui')

vim.keymap.set('n', "'a", mark.add_file)
vim.keymap.set('n', "'r", ui.toggle_quick_menu)
vim.keymap.set('n', "'q", function()
  ui.nav_file(1)
end)
vim.keymap.set('n', "'w", function()
  ui.nav_file(2)
end)
vim.keymap.set('n', "'q", function()
  ui.nav_file(1)
end)
vim.keymap.set('n', "'e", function()
  ui.nav_file(3)
end)
